/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as MiniPanelRouteImport } from './routes/mini-panel'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as GatewaysIndexRouteImport } from './routes/gateways/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CliIndexRouteImport } from './routes/cli/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as BackupsIndexRouteImport } from './routes/backups/index'
import { Route as GatewaysSettingsRouteImport } from './routes/gateways/settings'
import { Route as GatewaysProvidersRouteImport } from './routes/gateways/providers'
import { Route as GatewaysModelsRouteImport } from './routes/gateways/models'
import { Route as CommunityAdminRouteImport } from './routes/community/admin'
import { Route as CommunityPostIdRouteImport } from './routes/community/post.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniPanelRoute = MiniPanelRouteImport.update({
  id: '/mini-panel',
  path: '/mini-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaysIndexRoute = GatewaysIndexRouteImport.update({
  id: '/gateways/',
  path: '/gateways/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CliIndexRoute = CliIndexRouteImport.update({
  id: '/cli/',
  path: '/cli/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsIndexRoute = BackupsIndexRouteImport.update({
  id: '/backups/',
  path: '/backups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaysSettingsRoute = GatewaysSettingsRouteImport.update({
  id: '/gateways/settings',
  path: '/gateways/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaysProvidersRoute = GatewaysProvidersRouteImport.update({
  id: '/gateways/providers',
  path: '/gateways/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaysModelsRoute = GatewaysModelsRouteImport.update({
  id: '/gateways/models',
  path: '/gateways/models',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAdminRoute = CommunityAdminRouteImport.update({
  id: '/community/admin',
  path: '/community/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/community/post/$id',
  path: '/community/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browser': typeof BrowserRoute
  '/mini-panel': typeof MiniPanelRoute
  '/preview': typeof PreviewRoute
  '/settings': typeof SettingsRoute
  '/community/admin': typeof CommunityAdminRoute
  '/gateways/models': typeof GatewaysModelsRoute
  '/gateways/providers': typeof GatewaysProvidersRoute
  '/gateways/settings': typeof GatewaysSettingsRoute
  '/backups/': typeof BackupsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/cli/': typeof CliIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/gateways/': typeof GatewaysIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/community/post/$id': typeof CommunityPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browser': typeof BrowserRoute
  '/mini-panel': typeof MiniPanelRoute
  '/preview': typeof PreviewRoute
  '/settings': typeof SettingsRoute
  '/community/admin': typeof CommunityAdminRoute
  '/gateways/models': typeof GatewaysModelsRoute
  '/gateways/providers': typeof GatewaysProvidersRoute
  '/gateways/settings': typeof GatewaysSettingsRoute
  '/backups': typeof BackupsIndexRoute
  '/chat': typeof ChatIndexRoute
  '/cli': typeof CliIndexRoute
  '/community': typeof CommunityIndexRoute
  '/gateways': typeof GatewaysIndexRoute
  '/logs': typeof LogsIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/community/post/$id': typeof CommunityPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browser': typeof BrowserRoute
  '/mini-panel': typeof MiniPanelRoute
  '/preview': typeof PreviewRoute
  '/settings': typeof SettingsRoute
  '/community/admin': typeof CommunityAdminRoute
  '/gateways/models': typeof GatewaysModelsRoute
  '/gateways/providers': typeof GatewaysProvidersRoute
  '/gateways/settings': typeof GatewaysSettingsRoute
  '/backups/': typeof BackupsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/cli/': typeof CliIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/gateways/': typeof GatewaysIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/community/post/$id': typeof CommunityPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browser'
    | '/mini-panel'
    | '/preview'
    | '/settings'
    | '/community/admin'
    | '/gateways/models'
    | '/gateways/providers'
    | '/gateways/settings'
    | '/backups/'
    | '/chat/'
    | '/cli/'
    | '/community/'
    | '/gateways/'
    | '/logs/'
    | '/workspaces/'
    | '/community/post/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browser'
    | '/mini-panel'
    | '/preview'
    | '/settings'
    | '/community/admin'
    | '/gateways/models'
    | '/gateways/providers'
    | '/gateways/settings'
    | '/backups'
    | '/chat'
    | '/cli'
    | '/community'
    | '/gateways'
    | '/logs'
    | '/workspaces'
    | '/community/post/$id'
  id:
    | '__root__'
    | '/'
    | '/browser'
    | '/mini-panel'
    | '/preview'
    | '/settings'
    | '/community/admin'
    | '/gateways/models'
    | '/gateways/providers'
    | '/gateways/settings'
    | '/backups/'
    | '/chat/'
    | '/cli/'
    | '/community/'
    | '/gateways/'
    | '/logs/'
    | '/workspaces/'
    | '/community/post/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowserRoute: typeof BrowserRoute
  MiniPanelRoute: typeof MiniPanelRoute
  PreviewRoute: typeof PreviewRoute
  SettingsRoute: typeof SettingsRoute
  CommunityAdminRoute: typeof CommunityAdminRoute
  GatewaysModelsRoute: typeof GatewaysModelsRoute
  GatewaysProvidersRoute: typeof GatewaysProvidersRoute
  GatewaysSettingsRoute: typeof GatewaysSettingsRoute
  BackupsIndexRoute: typeof BackupsIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  CliIndexRoute: typeof CliIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  GatewaysIndexRoute: typeof GatewaysIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
  CommunityPostIdRoute: typeof CommunityPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-panel': {
      id: '/mini-panel'
      path: '/mini-panel'
      fullPath: '/mini-panel'
      preLoaderRoute: typeof MiniPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateways/': {
      id: '/gateways/'
      path: '/gateways'
      fullPath: '/gateways/'
      preLoaderRoute: typeof GatewaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/': {
      id: '/cli/'
      path: '/cli'
      fullPath: '/cli/'
      preLoaderRoute: typeof CliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups/': {
      id: '/backups/'
      path: '/backups'
      fullPath: '/backups/'
      preLoaderRoute: typeof BackupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateways/settings': {
      id: '/gateways/settings'
      path: '/gateways/settings'
      fullPath: '/gateways/settings'
      preLoaderRoute: typeof GatewaysSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateways/providers': {
      id: '/gateways/providers'
      path: '/gateways/providers'
      fullPath: '/gateways/providers'
      preLoaderRoute: typeof GatewaysProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateways/models': {
      id: '/gateways/models'
      path: '/gateways/models'
      fullPath: '/gateways/models'
      preLoaderRoute: typeof GatewaysModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/admin': {
      id: '/community/admin'
      path: '/community/admin'
      fullPath: '/community/admin'
      preLoaderRoute: typeof CommunityAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/post/$id': {
      id: '/community/post/$id'
      path: '/community/post/$id'
      fullPath: '/community/post/$id'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowserRoute: BrowserRoute,
  MiniPanelRoute: MiniPanelRoute,
  PreviewRoute: PreviewRoute,
  SettingsRoute: SettingsRoute,
  CommunityAdminRoute: CommunityAdminRoute,
  GatewaysModelsRoute: GatewaysModelsRoute,
  GatewaysProvidersRoute: GatewaysProvidersRoute,
  GatewaysSettingsRoute: GatewaysSettingsRoute,
  BackupsIndexRoute: BackupsIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  CliIndexRoute: CliIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  GatewaysIndexRoute: GatewaysIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
  CommunityPostIdRoute: CommunityPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
